# This is a basic workflow to help you get started with Actions

name: PullImagesTask

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Runner pull k8s.gcr.io images.
        run: |
          docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343@sha256:39c5b2e3310dc4264d638ad28d9d1d96c4cbb2b2dcfb52368fe4e3c63f61e10f
          docker pull registry.k8s.io/ingress-nginx/controller:v1.4.0@sha256:34ee929b111ffc7aa426ffd409af44da48e5a0eea1eb2207994d9e0c0882d143
          docker tag registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343@sha256:39c5b2e3310dc4264d638ad28d9d1d96c4cbb2b2dcfb52368fe4e3c63f61e10f registry.cn-beijing.aliyuncs.com/gcrios/metrics-server:kube-webhook-certgen
          docker tag registry.k8s.io/ingress-nginx/controller:v1.4.0@sha256:34ee929b111ffc7aa426ffd409af44da48e5a0eea1eb2207994d9e0c0882d143 registry.cn-beijing.aliyuncs.com/gcrios/metrics-server:controller
      - name: LoadAliyun Image Service & Push images.
        run: |
          docker login --username=${{ secrets.ALIYUNUSERNAME }} --password=${{ secrets.ALIYUNPASSWORD }} registry.cn-beijing.aliyuncs.com
          docker push registry.cn-beijing.aliyuncs.com/gcrios/metrics-server:kube-webhook-certgen
          docekr push registry.cn-beijing.aliyuncs.com/gcrios/metrics-server:controller
      - name: push completions.
        run: |
          echo "Push Image Completion!!!"
